{
 "title": "soil moisture",
 "time": { "from": "2023-10-26T23:53:06.696Z", "to": "2023-10-27T05:49:43.435Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "select * from temp" }
   ]
  },
  {
   "title": "Moisture",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * from moisture" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "query": "select * from temp" }
   ]
  },
  {
   "title": "Moisture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    { "query": "select * from moisture" }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "query": "select * from temp" }
   ]
  },
  {
   "title": "Moisture",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "query": "SELECT * from moisture" }
   ]
  },
  {
   "title": "Average value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "select * from \"average value\";\n"
    }
   ]
  },
  {
   "title": "Degree of stability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "select * from \"Degree of stability\";"
    }
   ]
  },
  {
   "title": "Rate of change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 32 },
   "targets": [
    {
     "query": "select * from \"Rate of change\";\n"
    }
   ]
  }
 ]
}